In [999]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [1000]:
dt = pd.read_csv('covid_worldwide.csv')
dt.head()

Serial Number  Country  Total Cases Total Deaths Total Recovered  \
0              1      USA  104,196,861    1,132,935     101,322,779   
1              2    India   44,682,784      530,740      44,150,289   
2              3   France   39,524,311      164,233      39,264,546   
3              4  Germany   37,779,833      165,711      37,398,100   
4              5   Brazil   36,824,580      697,074      35,919,372   

  Active Cases     Total Test     Population  
0    1,741,147  1,159,832,679    334,805,269  
1        1,755    915,265,788  1,406,631,776  
2       95,532    271,490,188     65,584,518  
3      216,022    122,332,384     83,883,596  
4      208,134     63,776,166    215,353,593

In [1001]:
dt.dtypes

Serial Number       int64
Country            object
Total Cases        object
Total Deaths       object
Total Recovered    object
Active Cases       object
Total Test         object
Population         object
dtype: object

In [1002]:
# dt['Total Cases'] = pd.to_numeric(dt['Total Cases'], errors='coerce', downcast='float')
# dt['Total Deaths'] = pd.to_numeric(dt['Total Deaths'], errors='coerce', downcast='float')
# dt['Total Recovered'] = pd.to_numeric(dt['Total Recovered'], errors='coerce', downcast='float')

dt['Total Cases'] = dt['Total Cases'].str.replace(',', '')
dt["Total Cases"] = dt["Total Cases"].astype(float)
dt["Total Cases"] = dt["Total Cases"] / 1000000

dt['Total Deaths'] = dt['Total Deaths'].str.replace(',', '')
dt["Total Deaths"] = dt["Total Deaths"].astype(float)
dt["Total Deaths"] = dt["Total Deaths"] / 1000000

dt['Total Recovered'] = dt['Total Recovered'].str.replace(',', '')
dt["Total Recovered"] = dt["Total Recovered"].astype(float)
dt["Total Recovered"] = dt["Total Recovered"] / 1000000

dt['Active Cases'] = dt['Active Cases'].str.replace(',', '')
dt["Active Cases"] = dt["Active Cases"].astype(float)
dt["Active Cases"] = dt["Active Cases"] / 1000000

dt['Population'] = dt['Population'].str.replace(',', '')
dt["Population"] = dt["Population"].astype(float)
dt["Population"] = dt["Population"] / 1000000



In [1003]:
irisData = dt.drop(['Total Test'], axis=1)
irisData.head()

Serial Number  Country  Total Cases  Total Deaths  Total Recovered  \
0              1      USA   104.196861      1.132935       101.322779   
1              2    India    44.682784      0.530740        44.150289   
2              3   France    39.524311      0.164233        39.264546   
3              4  Germany    37.779833      0.165711        37.398100   
4              5   Brazil    36.824580      0.697074        35.919372   

   Active Cases   Population  
0      1.741147   334.805269  
1      0.001755  1406.631776  
2      0.095532    65.584518  
3      0.216022    83.883596  
4      0.208134   215.353593

In [1004]:
irisData.dtypes

Serial Number        int64
Country             object
Total Cases        float64
Total Deaths       float64
Total Recovered    float64
Active Cases       float64
Population         float64
dtype: object

In [1005]:
irisData.isnull().sum()

Serial Number       0
Country             0
Total Cases         0
Total Deaths        6
Total Recovered    21
Active Cases       19
Population          3
dtype: int64

In [1006]:
x = irisData.iloc[: , 2:5].values
y = irisData.iloc[:, -2:].values

In [1007]:
print(x)

[[1.04196861e+02 1.13293500e+00 1.01322779e+02]
 [4.46827840e+01 5.30740000e-01 4.41502890e+01]
 [3.95243110e+01 1.64233000e-01 3.92645460e+01]
 [3.77798330e+01 1.65711000e-01 3.73981000e+01]
 [3.68245800e+01 6.97074000e-01 3.59193720e+01]
 [3.25884420e+01 6.83990000e-02 2.15674250e+01]
 [3.01970660e+01 3.34860000e-02 2.97408770e+01]
 [2.54537890e+01 1.86833000e-01 2.50149860e+01]
 [2.42743610e+01 2.04171000e-01 2.40200880e+01]
 [2.19586960e+01 3.95108000e-01 2.13560080e+01]
 [1.70427220e+01 1.01492000e-01            nan]
 [1.37314780e+01 1.18434000e-01 1.35576990e+01]
 [1.15265080e+01 4.31860000e-02 1.06124790e+01]
 [1.12954460e+01 1.86150000e-02 1.12357710e+01]
 [1.00371350e+01 1.30421000e-01 9.87703200e+00]
 [9.56961100e+00 1.63560000e-02 9.12976600e+00]
 [8.58250000e+00 2.29890000e-02 8.54777100e+00]
 [7.56435000e+00 1.44749000e-01 7.33754900e+00]
 [7.36825200e+00 3.32198000e-01 6.60663300e+00]
 [6.73028900e+00 1.60817000e-01 6.56520800e+00]
 [6.38022500e+00 1.18736000e-01 5.335940

In [1008]:
print(y)

[[1.74114700e+00 3.34805269e+02]
 [1.75500000e-03 1.40663178e+03]
 [9.55320000e-02 6.55845180e+01]
 [2.16022000e-01 8.38835960e+01]
 [2.08134000e-01 2.15353593e+02]
 [1.09526180e+01 1.25584838e+02]
 [4.22703000e-01 5.13298990e+01]
 [2.51970000e-01 6.02627700e+01]
 [5.01020000e-02 6.84979070e+01]
 [2.07580000e-01 1.45805947e+02]
 [           nan 8.55619760e+01]
 [5.53450000e-02 4.67191420e+01]
 [8.70843000e-01 9.89535410e+01]
 [4.10600000e-02 2.60687920e+01]
 [2.96820000e-02 4.60102340e+01]
 [4.23489000e-01 2.38885950e+01]
 [1.17400000e-02 1.72114470e+01]
 [8.20520000e-02 8.60228370e+01]
 [4.29421000e-01 1.31562772e+02]
 [4.26400000e-03 2.79134505e+02]
 [9.25549000e-01 3.77397850e+01]
 [3.43220000e-02 5.15127620e+01]
 [2.83510000e-02 9.06671000e+00]
 [1.04590000e-02 1.03166370e+01]
 [5.51900000e-03 1.01405700e+01]
 [5.80900000e-03 4.31921220e+01]
 [3.61400000e-03 1.92501950e+01]
 [9.79000000e-03 3.31810720e+01]
 [5.75400000e-03 9.32600000e+00]
 [0.00000000e+00 2.59906790e+01]
 [4.830000

In [1009]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 2:5])
x[:, 2:5] = imputer.transform(x[:, 2:5])
x

array([[1.04196861e+02, 1.13293500e+00, 1.01322779e+02],
       [4.46827840e+01, 5.30740000e-01, 4.41502890e+01],
       [3.95243110e+01, 1.64233000e-01, 3.92645460e+01],
       [3.77798330e+01, 1.65711000e-01, 3.73981000e+01],
       [3.68245800e+01, 6.97074000e-01, 3.59193720e+01],
       [3.25884420e+01, 6.83990000e-02, 2.15674250e+01],
       [3.01970660e+01, 3.34860000e-02, 2.97408770e+01],
       [2.54537890e+01, 1.86833000e-01, 2.50149860e+01],
       [2.42743610e+01, 2.04171000e-01, 2.40200880e+01],
       [2.19586960e+01, 3.95108000e-01, 2.13560080e+01],
       [1.70427220e+01, 1.01492000e-01, 2.99390513e+00],
       [1.37314780e+01, 1.18434000e-01, 1.35576990e+01],
       [1.15265080e+01, 4.31860000e-02, 1.06124790e+01],
       [1.12954460e+01, 1.86150000e-02, 1.12357710e+01],
       [1.00371350e+01, 1.30421000e-01, 9.87703200e+00],
       [9.56961100e+00, 1.63560000e-02, 9.12976600e+00],
       [8.58250000e+00, 2.29890000e-02, 8.54777100e+00],
       [7.56435000e+00, 1.44749

In [1010]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(y[:, -2:])
y[:, -2:] = imputer.transform(y[:, -2:])
y

array([[1.74114700e+00, 3.34805269e+02],
       [1.75500000e-03, 1.40663178e+03],
       [9.55320000e-02, 6.55845180e+01],
       [2.16022000e-01, 8.38835960e+01],
       [2.08134000e-01, 2.15353593e+02],
       [1.09526180e+01, 1.25584838e+02],
       [4.22703000e-01, 5.13298990e+01],
       [2.51970000e-01, 6.02627700e+01],
       [5.01020000e-02, 6.84979070e+01],
       [2.07580000e-01, 1.45805947e+02],
       [9.09988491e-02, 8.55619760e+01],
       [5.53450000e-02, 4.67191420e+01],
       [8.70843000e-01, 9.89535410e+01],
       [4.10600000e-02, 2.60687920e+01],
       [2.96820000e-02, 4.60102340e+01],
       [4.23489000e-01, 2.38885950e+01],
       [1.17400000e-02, 1.72114470e+01],
       [8.20520000e-02, 8.60228370e+01],
       [4.29421000e-01, 1.31562772e+02],
       [4.26400000e-03, 2.79134505e+02],
       [9.25549000e-01, 3.77397850e+01],
       [3.43220000e-02, 5.15127620e+01],
       [2.83510000e-02, 9.06671000e+00],
       [1.04590000e-02, 1.03166370e+01],
       [5.519000

In [1011]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=15, train_size=5)

In [1012]:
x_train

array([[1.1295446e+01, 1.8615000e-02, 1.1235771e+01],
       [1.2954260e+00, 3.8179000e-02, 1.2544910e+00],
       [5.1564500e-01, 2.4613000e-02, 4.4218200e-01],
       [3.7491000e-02, 8.3300000e-04, 3.6366000e-02],
       [2.5453789e+01, 1.8683300e-01, 2.5014986e+01]])

In [1013]:
x_test

array([[1.186176e+00, 9.158000e-03, 8.607110e-01],
       [1.330900e-01, 1.468000e-03, 1.315590e-01],
       [5.033020e-01, 5.272000e-03, 3.790530e-01],
       [5.008000e-03, 1.800000e-05, 2.703000e-03],
       [3.427000e-03, 7.000000e-06, 4.380000e-04],
       [3.292270e-01, 2.800000e-03, 3.259340e-01],
       [2.877280e+00, 1.335800e-02, 2.509483e+00],
       [2.537500e-02, 3.860000e-04, 2.400600e-02],
       [8.890200e-02, 1.971000e-03, 8.692900e-02],
       [2.134000e-02, 8.900000e-05, 2.123700e-02],
       [5.036593e+00, 3.694200e-02, 4.989861e+00],
       [1.849100e-02, 2.250000e-04, 4.225000e-03],
       [5.118981e+00, 6.381200e-02, 5.051555e+00],
       [4.858950e-01, 9.190000e-04, 4.185720e-01],
       [3.935400e-02, 2.900000e-04, 3.906100e-02]])

In [1014]:
y_test

array([[3.1630700e-01, 5.1823540e+00],
       [6.3000000e-05, 1.3600464e+01],
       [1.1897700e-01, 2.8493262e+01],
       [2.2870000e-03, 1.2341900e-01],
       [2.9820000e-03, 1.0982000e-02],
       [4.9300000e-04, 2.4411620e+00],
       [3.5443900e-01, 7.6042990e+00],
       [9.8300000e-04, 5.7978050e+00],
       [2.0000000e-06, 1.7653671e+01],
       [1.4000000e-05, 3.8387000e-02],
       [9.7900000e-03, 3.3181072e+01],
       [1.4041000e-02, 6.7791000e+00],
       [3.6140000e-03, 1.9250195e+01],
       [6.6404000e-02, 9.0806100e-01],
       [3.0000000e-06, 8.6808370e+00]])

In [1015]:
y_train

array([[4.10600000e-02, 2.60687920e+01],
       [2.75600000e-03, 6.84459700e+00],
       [4.88500000e-02, 1.06156692e+02],
       [2.92000000e-04, 4.00516000e-01],
       [2.51970000e-01, 6.02627700e+01]])

In [1016]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 1:] = sc.fit_transform(x_train[:, 1:])
x_test[:, 1:] = sc.fit_transform(x_test[:, 1:])

y_train[:, 1:] = sc.fit_transform(y_train[:, 1:])
y_test[:, 1:] = sc.fit_transform(y_test[:, 1:])


In [1017]:
from feature_engine.imputation import RandomSampleImputer
imputer = RandomSampleImputer()
imputer.fit(x_test)
test_t = imputer.transform(x_test)
test_t

x0        x1        x2
0   1.186176  0.002522 -0.075987
1   0.133090 -0.441671 -0.505567
2   0.503302 -0.221942 -0.359756
3   0.005008 -0.525426 -0.581482
4   0.003427 -0.526062 -0.582816
5   0.329227 -0.364731 -0.391051
6   2.877280  0.245124  0.895386
7   0.025375 -0.504170 -0.568931
8   0.088902 -0.412616 -0.531860
9   0.021340 -0.521325 -0.570563
10  5.036593  1.607393  2.356700
11  0.018491 -0.513469 -0.580585
12  5.118981  3.159470  2.393047
13  0.485895 -0.473382 -0.336473
14  0.039354 -0.509715 -0.560062

In [1018]:
print(x_train)

[[11.295446   -0.5208368   0.37726321]
 [ 1.295426   -0.23135479 -0.65751489]
 [ 0.515645   -0.43208639 -0.74172849]
 [ 0.037491   -0.78395116 -0.7838002 ]
 [25.453789    1.96822913  1.80578037]]


In [1019]:
print(x_test)

[[ 1.18617600e+00  2.52229254e-03 -7.59870179e-02]
 [ 1.33090000e-01 -4.41670752e-01 -5.05566599e-01]
 [ 5.03302000e-01 -2.21942489e-01 -3.59755617e-01]
 [ 5.00800000e-03 -5.25426267e-01 -5.81482055e-01]
 [ 3.42700000e-03 -5.26061654e-01 -5.82816479e-01]
 [ 3.29227000e-01 -3.64731202e-01 -3.91050653e-01]
 [ 2.87728000e+00  2.45124475e-01  8.95386283e-01]
 [ 2.53750000e-02 -5.04169695e-01 -5.68931402e-01]
 [ 8.89020000e-02 -4.12616252e-01 -5.31860344e-01]
 [ 2.13400000e-02 -5.21325135e-01 -5.70562757e-01]
 [ 5.03659300e+00  1.60739349e+00  2.35669989e+00]
 [ 1.84910000e-02 -5.13469445e-01 -5.80585369e-01]
 [ 5.11898100e+00  3.15946984e+00  2.39304689e+00]
 [ 4.85895000e-01 -4.73382323e-01 -3.36473016e-01]
 [ 3.93540000e-02 -5.09714888e-01 -5.60061755e-01]]


In [1020]:
print(y_test)

[[ 3.16307000e-01 -4.75094808e-01]
 [ 6.30000000e-05  3.58000668e-01]
 [ 1.18977000e-01  1.83186150e+00]
 [ 2.28700000e-03 -9.75750639e-01]
 [ 2.98200000e-03 -9.86877929e-01]
 [ 4.93000000e-04 -7.46375968e-01]
 [ 3.54439000e-01 -2.35407821e-01]
 [ 9.83000000e-04 -4.14186903e-01]
 [ 2.00000000e-06  7.59124960e-01]
 [ 1.40000000e-05 -9.84165803e-01]
 [ 9.79000000e-03  2.29578907e+00]
 [ 1.40410000e-02 -3.17073367e-01]
 [ 3.61400000e-03  9.17124431e-01]
 [ 6.64040000e-02 -8.98098803e-01]
 [ 3.00000000e-06 -1.28868593e-01]]


In [1021]:
print(y_train)

[[ 4.10600000e-02 -3.54823916e-01]
 [ 2.75600000e-03 -8.46340162e-01]
 [ 4.88500000e-02  1.69283030e+00]
 [ 2.92000000e-04 -1.01109975e+00]
 [ 2.51970000e-01  5.19433533e-01]]
